global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: "default"
  routes:
    - match:
        severity: critical
      receiver: "critical"
    - match:
        severity: warning
      receiver: "warning"

receivers:
  - name: "default"
    webhook_configs:
      - url: "http://localhost:5001/alerts"

  - name: "critical"
    email_configs:
      - to: "alerts@travion.com"
        from: "alertmanager@travion.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "alertmanager@travion.com"
        auth_password: "your-password"
        headers:
          Subject: "CRITICAL: {{ .GroupLabels.alertname }}"

  - name: "warning"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#alerts"
        title: "Warning: {{ .GroupLabels.alertname }}"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "cluster", "service"]
