apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
data:
  PYTHON_ENV: "production"
  PORT: "8000"
  LOG_LEVEL: "INFO"
