# ⚠️ DO NOT commit actual secrets to Git
# This is an example file showing the structure

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:password@mongodb:27017/travion?authSource=admin"
  JWT_SECRET: "your_jwt_secret_here"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  username: "admin"
  password: "change_this_password"
