---
- name: Setup Travion Server
  hosts: travion_servers
  become: yes
  vars:
    app_dir: /opt/travion
    docker_compose_version: "2.23.0"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Clone repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Copy environment files
      copy:
        src: "{{ app_dir }}/infrastructure/{{ item }}.example"
        dest: "{{ app_dir }}/infrastructure/{{ item }}"
        remote_src: yes
      loop:
        - .env
        - docker/backend/.env
        - docker/ml-services/.env

    - name: Start Docker services
      command: docker-compose -f {{ app_dir }}/infrastructure/compose/docker-compose.prod.yml up -d
      args:
        chdir: "{{ app_dir }}"
