version: "3.8"

# Override file for local development
# Automatically merged with docker-compose.dev.yml

services:
  backend:
    command: npm run dev
    environment:
      - DEBUG=*

  # Database management UI
  mongo-express:
    image: mongo-express:latest
    container_name: travion-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpassword123
      ME_CONFIG_MONGODB_URL: mongodb://admin:devpassword123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - travion-net
